## SPRING CONFIG SERVER
spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/<--username-->/git-config-repository.git
          username: <--username-->
          password: <--password-->
          cloneOnStart: true
          
